#!/bin/sh

# colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

CURRENT_SWAG_VERSION=$(swag --version 2>&1)

REQUIRED_SWAG_VERSION="v1.8.4"

if [[ "$CURRENT_SWAG_VERSION" != *"$REQUIRED_SWAG_VERSION"* ]]; then
    printf "${RED}Swagger version is not %s.${NC}\n" "$REQUIRED_SWAG_VERSION"
    exit 1
fi

make swagger

if [ $? -ne 0 ]; then
    printf "${RED}Swagger generation failed. Aborting commit.${NC}\n"
    exit 1
else
    printf "${GREEN}Swagger docs generation/update successful.${NC}\n"
fi

exit 0